version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_H2_CONSOLE_PATH=/h2
    depends_on:
      - db

  db:
    image: buildo/h2database
    ports:
      - 1521:1521
      - 81:81
    environment:
      - H2_CONSOLE_ENABLED=true
